---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 387918187-dyck69lWRcS7APEAbBOykfDZvJihxr9efUCPTSb6
:access_token_secret: q6267CxAy0ccUAteLgburgKUSYMvUuq8XfAjboja64XcF
